name: Flutter Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ios:
    permissions: write-all
    name: Build iOS application
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: |
        cd frontend
        flutter clean
        rm -Rf ios/Pods
        rm -Rf ios/.symlinks
        rm -Rf ios/Flutter/Flutter.framework
        rm -Rf ios/Flutter/Flutter.podspec
        flutter pub get
    - run: flutter build ios --release --no-codesign -v
    - run: |
        mkdir /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/ios/iphoneos/Payload
        cp -r /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/ios/iphoneos/Runner.app /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/ios/iphoneos/Payload/
        cd /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/ios/iphoneos/
        zip -r Payload.zip Payload
        mv Payload.zip SpeechSummarizer.ipa
    - id: flutter-action
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: |
        echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
        echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
        echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
        echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
        echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: SpeechSummarizer.ipa
        path: |
          /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/ios/iphoneos/SpeechSummarizer.ipa
    - uses: IsaacShelton/update-existing-release@v1.3.1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        release: "Nightly iOS Release"
        tag: "nightly"
        prerelease: true
        replace: true
        files: >
          /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/ios/iphoneos/SpeechSummarizer.ipa

  android:
    name: Build android application
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: |
        cd frontend
        flutter clean
        flutter pub get
    - run: flutter build apk --split-per-abi --release -v
    - run: flutter build appbundle --release -v
    - id: flutter-action
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: |
        echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
        echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
        echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
        echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
        echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: Android Binaries
        path: |
          /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/app/outputs/flutter-apk/app-x86_64-release.apk
          /Users/runner/work/SpeechSummarizer/SpeechSummarizer/frontend/build/app/outputs/bundle/release/app-release.aab
